-- VERTX CORE v5.2 DB FIX
-- Safe to run once or rerun in Supabase > SQL Editor.

-- 1) Member roles
alter table public.memberships drop constraint if exists memberships_role_check;
alter table public.memberships add constraint memberships_role_check check (role in ('owner','admin','member','viewer'));

create or replace function public.list_organization_members(p_org uuid)
returns table(user_id uuid,email text,role text,created_at timestamptz)
language sql
security definer
set search_path=public,auth
as $$
  select m.user_id,u.email::text,m.role,m.created_at
  from public.memberships m
  join auth.users u on u.id=m.user_id
  where m.organization_id=p_org
    and public.is_org_member(p_org)
  order by case m.role when 'owner' then 0 when 'admin' then 1 when 'member' then 2 else 3 end,m.created_at;
$$;

create or replace function public.set_organization_member_role(p_org uuid,p_user uuid,p_role text)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare caller_role text; target_role text;
begin
  select role into caller_role from public.memberships where organization_id=p_org and user_id=auth.uid();
  select role into target_role from public.memberships where organization_id=p_org and user_id=p_user;
  if caller_role not in ('owner','admin') then raise exception 'permission denied'; end if;
  if p_role not in ('admin','member','viewer') then raise exception 'invalid role'; end if;
  if target_role='owner' then raise exception 'owner role cannot be changed here'; end if;
  if caller_role='admin' and (target_role='admin' or p_role='admin') then raise exception 'only owner can manage admins'; end if;
  update public.memberships set role=p_role where organization_id=p_org and user_id=p_user;
end;
$$;

grant execute on function public.list_organization_members(uuid) to authenticated;
grant execute on function public.set_organization_member_role(uuid,uuid,text) to authenticated;

-- 2) Subscription fields
alter table public.organizations add column if not exists plan text not null default 'standard';
alter table public.organizations add column if not exists subscription_status text not null default 'trial';
alter table public.organizations add column if not exists trial_ends_at timestamptz default (now() + interval '30 days');
alter table public.organizations add column if not exists billing_customer_id text;
alter table public.organizations add column if not exists billing_subscription_id text;
alter table public.organizations add column if not exists ai_monthly_limit integer not null default 30;
alter table public.organizations add column if not exists ai_used_this_month integer not null default 0;

-- Test-mode plan switch. Owner only. Replace this RPC with billing webhook control when paid subscriptions go live.
create or replace function public.set_organization_plan(p_org uuid,p_plan text)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare caller_role text;
begin
  select role into caller_role from public.memberships where organization_id=p_org and user_id=auth.uid();
  if caller_role <> 'owner' then raise exception 'only owner can change plan'; end if;
  if p_plan not in ('free','standard','pro') then raise exception 'invalid plan'; end if;
  update public.organizations
  set plan=p_plan, subscription_status='trial'
  where id=p_org;
end;
$$;
grant execute on function public.set_organization_plan(uuid,text) to authenticated;

-- 3) Company-specific AI learning memory
create table if not exists public.ai_learning_examples (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source_type text not null default 'confirmed_order',
  context text not null default '',
  corrected_materials jsonb not null default '[]'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
alter table public.ai_learning_examples enable row level security;
drop policy if exists ai_learning_examples_org on public.ai_learning_examples;
create policy ai_learning_examples_org on public.ai_learning_examples for all to authenticated
using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));
create index if not exists ai_learning_examples_org_idx on public.ai_learning_examples(organization_id,created_at desc);

-- 4) IMPORTANT: this app does NOT use public.materials.
-- Material master is stored per-company in tenant_store JSON, so do not DELETE FROM public.materials.
-- Obsolete materials are filtered/migrated by the v5.2 app code itself.

notify pgrst, 'reload schema';
