import crypto from 'node:crypto';
import {json,serviceUpdateOrganization,stripeGet} from '../lib/billing.js';
export const config={api:{bodyParser:false}};
async function raw(req){const chunks=[];for await(const c of req)chunks.push(Buffer.isBuffer(c)?c:Buffer.from(c));return Buffer.concat(chunks)}
function verify(body,sig,secret){const parts=Object.fromEntries(String(sig||'').split(',').map(x=>x.split('=')));const t=parts.t,v1=String(sig||'').split(',').find(x=>x.startsWith('v1='))?.slice(3);if(!t||!v1)throw new Error('Stripe署名がありません');if(Math.abs(Date.now()/1000-Number(t))>300)throw new Error('Stripe署名の時刻が不正です');const expected=crypto.createHmac('sha256',secret).update(`${t}.${body.toString('utf8')}`).digest('hex');const a=Buffer.from(expected),b=Buffer.from(v1);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw new Error('Stripe署名を確認できません')}
function mapStatus(s){if(['active','trialing'].includes(s))return 'active';if(['past_due','unpaid','incomplete','incomplete_expired'].includes(s))return 'past_due';if(['canceled','paused'].includes(s))return 'canceled';return s||'active'}
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{error:'POST only'});try{const secret=process.env.STRIPE_WEBHOOK_SECRET||'';if(!secret)return json(res,503,{error:'Webhook secret missing'});const body=await raw(req);verify(body,req.headers['stripe-signature'],secret);const event=JSON.parse(body.toString('utf8'));const o=event.data?.object||{};
  if(event.type==='checkout.session.completed'&&o.mode==='subscription'){const orgId=o.metadata?.org_id||o.client_reference_id,plan=o.metadata?.plan||'standard';let sub=null;try{sub=o.subscription?await stripeGet(`subscriptions/${o.subscription}`):null}catch{};if(orgId)await serviceUpdateOrganization(orgId,{plan,subscription_status:mapStatus(sub?.status||'active'),billing_customer_id:String(o.customer||''),billing_subscription_id:String(o.subscription||''),billing_period_end:sub?.current_period_end?new Date(sub.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(sub?.cancel_at_period_end)});}
  if(event.type.startsWith('customer.subscription.')){const orgId=o.metadata?.org_id,plan=o.metadata?.plan;if(orgId)await serviceUpdateOrganization(orgId,{...(plan?{plan}:{}),subscription_status:mapStatus(o.status),billing_customer_id:String(o.customer||''),billing_subscription_id:String(o.id||''),billing_period_end:o.current_period_end?new Date(o.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(o.cancel_at_period_end)});}
  if(event.type==='invoice.payment_failed'){const subId=typeof o.subscription==='string'?o.subscription:o.subscription?.id;if(subId){const sub=await stripeGet(`subscriptions/${subId}`);const orgId=sub.metadata?.org_id;if(orgId)await serviceUpdateOrganization(orgId,{subscription_status:'past_due'});}}
  if(event.type==='invoice.paid'){const subId=typeof o.subscription==='string'?o.subscription:o.subscription?.id;if(subId){const sub=await stripeGet(`subscriptions/${subId}`);const orgId=sub.metadata?.org_id;if(orgId)await serviceUpdateOrganization(orgId,{subscription_status:mapStatus(sub.status),billing_period_end:sub.current_period_end?new Date(sub.current_period_end*1000).toISOString():null,cancel_at_period_end:Boolean(sub.cancel_at_period_end)});}}
  return json(res,200,{received:true});
}catch(e){return json(res,400,{error:e.message||'Webhook error'});}}
